name: Test on push

on:
  push:
  pull_request:
    branches:
      - master

jobs:

  generate_usage:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Show usage
      run: /bin/bash ./lysithea help
